// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShiftTracker.Data;

#nullable disable

namespace ShiftTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221231032335_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShiftTracker.Areas.Shifts.Models.Break", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.ToTable("Breaks", (string)null);
                });

            modelBuilder.Entity("ShiftTracker.Areas.Shifts.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RunId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("TotalBreakLength")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TotalDriveLength")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TotalShiftLength")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TotalWorkLength")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Shifts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            EndTime = new DateTime(2019, 1, 1, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            RunId = 68,
                            StartTime = new DateTime(2019, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalBreakLength = new TimeSpan(30),
                            TotalDriveLength = new TimeSpan(4),
                            TotalShiftLength = new TimeSpan(8),
                            TotalWorkLength = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            Id = -2,
                            EndTime = new DateTime(2019, 1, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            RunId = 68,
                            StartTime = new DateTime(2019, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalBreakLength = new TimeSpan(15),
                            TotalDriveLength = new TimeSpan(1),
                            TotalShiftLength = new TimeSpan(4),
                            TotalWorkLength = new TimeSpan(0, 2, 45, 0, 0)
                        },
                        new
                        {
                            Id = -3,
                            EndTime = new DateTime(2019, 1, 1, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            RunId = 68,
                            StartTime = new DateTime(2019, 1, 1, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalBreakLength = new TimeSpan(0, 1, 0, 0, 0),
                            TotalDriveLength = new TimeSpan(6),
                            TotalShiftLength = new TimeSpan(12),
                            TotalWorkLength = new TimeSpan(0, 5, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("ShiftTracker.Areas.Shifts.Models.Break", b =>
                {
                    b.HasOne("ShiftTracker.Areas.Shifts.Models.Shift", "Shift")
                        .WithMany("Breaks")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("ShiftTracker.Areas.Shifts.Models.Shift", b =>
                {
                    b.Navigation("Breaks");
                });
#pragma warning restore 612, 618
        }
    }
}
